Лабораторная работа 2
Veronika45-tech/razrabotchikponaPython pull request #2
Opened 2024-10-25 22:38 UTC by Veronika45-tech

![image](https://github.com/user-attachments/assets/8d4b95ea-d212-4ba6-b143-41d0887053c7)

2024-10-29 08:41 UTC, rmushkin requested changes
Есть микрозамечание по первой задаче и замечание по второй, пожалуйста, поправьте

2024-10-29 08:41 UTC, rmushkin commented on Лабораторная работа 2/2 finance.py
> +    if month >0:
PEP8

2024-10-29 08:41 UTC, rmushkin commented on Лабораторная работа 2/2 finance.py
> +money_capital = round(total_deficit)
А тут подстава с округлением. Трёх рублей не хватит, чтобы купить спичку за 3,25.

2024-10-29 08:41 UTC, rmushkin commented on Лабораторная работа 2/1 finance.py
> +while money_capital >= 0:
PEP8: у вас есть отступ внутри цикла, значит, перед циклом тоже логично сделать - ведь цикл точно логически обособлен больше, чем внутренние его части.

2024-10-29 22:10 UTC, Veronika45-tech commented on Лабораторная работа 2/2 finance.py
> +money_capital = round(total_deficit)
Здраствуйте! 
Скажите, пожалуйста, можно ли тогда здесь исползовать math.ceil()?
тогда будет округлении в большую... и хватить должно
Но на самом курсе не принимает такое

2024-10-31 09:10 UTC, rmushkin commented on Лабораторная работа 2/2 finance.py
> +money_capital = round(total_deficit)
Здравствуйте! Да) Именно.
К сожалению, в курсе есть ошибка. Мы уже обратились к авторам, чтобы они внесли исправления.

2024-10-31 22:20 UTC, Veronika45-tech commented on Лабораторная работа 2/2 finance.py
> +money_capital = round(total_deficit)
Спасибо большое

2024-11-01 19:51 UTC, rmushkin approved these changes
принимается ✅

2024-11-01 19:51 UTC, merged