Лабораторная работа 3
Veronika45-tech/razrabotchikponaPython pull request #3
Opened 2024-10-31 22:33 UTC by Veronika45-tech

![image](https://github.com/user-attachments/assets/5798e380-6759-4455-a809-16dea3f29590)

2024-11-07 16:42 UTC, rmushkin requested changes
Всего по немногу. Замечания не стращные, но, пожалуйста, исправьте. Если что, пишите с вопросами...

2024-11-07 16:42 UTC, rmushkin commented on лаба3/1index.py
> +
1. Хорошо, а если не нашли?
2. Какое свойсто языка Python позволяет вам избежать ошибки, несмотря на неправильность этого решения?
3. Какой пункт [Дзена Python](https://peps.python.org/pep-0020/) вы нарушаете?

2024-11-07 16:42 UTC, rmushkin commented on лаба3/2partic.py
> +print(participants_intersection)
Что, по-вашему, выведет программа?

2024-11-07 16:42 UTC, rmushkin commented on лаба3/3letter.py
> +    print(f"{letter}: {freq}")
А вот тут самое время играть с форматами

2024-11-07 16:42 UTC, rmushkin commented on лаба3/3letter.py
> +
PEP8...

2024-11-07 16:42 UTC, rmushkin commented on лаба3/3letter.py
> +    for letter in letter_count.keys():
Здесь вызывать `.keys()` не обязательно, так как словарь и так итерируется по своим ключам :)

2024-11-07 16:42 UTC, rmushkin commented on лаба3/3letter.py
> +        frequency[letter] = f"{freq:.2f}"
А вот это тут явно преждевременно. Частота - это число, и надо хранить его до последнего в самой точной из доступных форм (т. е. остаить как есть и не преобразовывать). А вот откруглениями и прочим вообще заниматься только непосредственно перед выводом.

2024-11-07 21:23 UTC, Veronika45-tech commented on лаба3/1index.py
> +
1. Исправила
2. Неявное преобразование типов
 is not None все равно возвращает True, так как None считается ложным значением 
3. Special cases aren't special enough to break the rules.

2024-11-07 22:50 UTC, rmushkin commented on лаба3/1index.py
> +
Мммммм, я бы рассудил не совсем так. 
2. То, что функция без return неявно возвращает None
3. Explicit is better than implicit.

2024-11-07 22:56 UTC, rmushkin requested changes
Увы, большая часть исправлений мимо :) Пожалуйста, ещё раунд!

2024-11-07 22:56 UTC, rmushkin commented on лаба3/1index.py
Ой, нет! Она как раз None и должна возвращать. Но пусть она делает это явно)

2024-11-07 22:56 UTC, rmushkin commented on лаба3/2partic.py
Оу, тут вы тоже сделали хуже.

2024-11-07 22:56 UTC, rmushkin commented on лаба3/2partic.py
> +def find_common_participants(group1, group2, delimiter='|'):
По условию разделитель по умолчанию - это как раз запятая. Это лишнее.

2024-11-07 22:56 UTC, rmushkin commented on лаба3/2partic.py
> +participants_intersection = find_common_participants(participants_first_group, participants_second_group, delimiter='|')
а вот это по делу.

2024-11-07 22:56 UTC, rmushkin commented on лаба3/3letter.py
> +        freq = round(letter_count[letter] / total_letters, 2) if total_letters > 0 else 0.00
Вы по-прежнему преждевременно округляете! Физический смысл (ещё говорят "бизнес-логика") ничего не говорит об округлении частоты (в отличие, например, от денег из прошлой лабораторной). Поэтому тут округлние - исключительно фишка вывода на экран.

2024-11-08 10:54 UTC, rmushkin approved these changes
Принимается ✅

2024-11-08 10:54 UTC, merged